### ISSUE TITLE
Lucio soy chucin

### ISSUE THREAD

**Issue by jesusedhas** [JCarlosLucio/yelp-camp#3]
que pedo we te he andado contactando por whats y nada me dijeron que por github podía contactarte xD

toy con el jose en un proyecto chido y quería platicar contigo para ver si te interesa entrarle al equipo, es proyecto de desarrollo de apps y también va abarcar videojuegos en algún punto, de principio igual y es entrarle a la estructura de trabajo que tenemos antes de programar, y sobre esa estructura se hace planeación con respecto a la programación, bueno como te conocemos estamos seguros de que tienes los skills necesarios pa entrarle al proyecto, k sientes

@JCarlosLucio

**Comment by JCarlosLucio** [comment]
Que onda Chuchin, 

> te he andado contactando por whats y nada me dijeron que por github podía contactarte xD

Si es que mi cel murio y ando consiguiendo otro 😅.

Y pues suena bien si quieren mañana podemos platicar de esto por _Discord_ o algo 🎧.
@jesusedhas

**Comment by jesusedhas** [comment]
aweeebo. Ya estas. Le pido tu id de discord al jose pa agregarte

**Comment by jesusedhas** [comment]
como a que hora te late? O bueno si quieres por discord nos pinemos se acuerdo, escríbele al jose si ya lo tienes
